# display_mode = "swap"
display_mode = "sync"
players = "spotify,vlc"
bind_address = "0.0.0.0:0"
host_address = "127.0.0.1:9000"
sync_message = "{meta} [{position}/{length}]"
sync_refresh_interval_seconds = 3
on_change_message = "Now Playing: {meta}"
send_immediately = true
notify_on_send = false
meta_format = "{{title}} - {{artist}} - {{album}}"